# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ghUserViewer' do
  pod 'AFNetworking', '3.1.0'
  pod 'Mantle', '2.0.7'
  pod 'SDWebImage', '3.8.1'
  pod 'PureLayout', '3.0.2'


  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ghUserViewer

  target 'ghUserViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ghUserViewerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
